-- USER TABLE
CREATE TABLE user (
  user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  login_id VARCHAR(15) NOT NULL,
  role ENUM('user', 'admin') NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Item
CREATE TABLE item (
  item_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  item_name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  category VARCHAR(25),
  stock INT NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Request
CREATE TABLE request (
    request_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- Request Detail
CREATE TABLE request_detail (
	request_detail_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	quantity INT NOT NULL,
    request_id INT UNSIGNED NOT NULL,
	item_id INT UNSIGNED NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT request_id FOREIGN KEY (request_id) REFERENCES request(request_id),
    CONSTRAINT item_id FOREIGN KEY (item_id) REFERENCES item(item_id)
);
